// File: app/src/main/kotlin/org/fossify/home/helpers/QrPairingProtocol.kt
// M1/M4: QR pairing crypto (RSA-2048 key exchange + AES-256-GCM command channel).
//
// NOTE (audit/M4 fix): QrPayloadJson.toJson/fromJson were stubs (fromJson returned a dummy).
// They now round-trip via org.json. Added launcher-side helpers (key encode/decode, RSA
// decrypt, AES key (de)serialisation) so the launcher can hold a keypair, publish its public
// key in a QR, receive an encrypted session key, and decrypt commands.

@file:Suppress("MagicNumber", "TooManyFunctions", "TooGenericExceptionCaught") // crypto sizes; fail-safe catches

package org.fossify.home.helpers

import android.util.Base64
import org.json.JSONObject
import java.security.KeyFactory
import java.security.KeyPair
import java.security.KeyPairGenerator
import java.security.PrivateKey
import java.security.PublicKey
import java.security.SecureRandom
import java.security.spec.PKCS8EncodedKeySpec
import java.security.spec.X509EncodedKeySpec
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

class QrPairingProtocol {

    companion object {
        const val PROTOCOL_VERSION = "1"
        const val RSA_KEY_SIZE = 2048
        const val AES_KEY_SIZE = 256
        const val NONCE_SIZE_BYTES = 16
        const val GCM_TAG_SIZE_BITS = 128
        const val GCM_IV_SIZE_BYTES = 12
    }

    // ─── Key management ──────────────────────────────────────────────────────────

    fun newKeyPair(): KeyPair = KeyPairGenerator.getInstance("RSA").apply {
        initialize(RSA_KEY_SIZE)
    }.generateKeyPair()

    fun encodeKey(bytes: ByteArray): String = Base64.encodeToString(bytes, Base64.NO_WRAP)
    fun decodeKey(b64: String): ByteArray = Base64.decode(b64, Base64.NO_WRAP)

    fun decodePublicKey(b64: String): PublicKey =
        KeyFactory.getInstance("RSA").generatePublic(X509EncodedKeySpec(decodeKey(b64)))

    fun decodePrivateKey(b64: String): PrivateKey =
        KeyFactory.getInstance("RSA").generatePrivate(PKCS8EncodedKeySpec(decodeKey(b64)))

    fun newNonceHex(): String {
        val nonce = ByteArray(NONCE_SIZE_BYTES)
        SecureRandom().nextBytes(nonce)
        return nonce.toHex()
    }

    // ─── RSA (session-key exchange) ─────────────────────────────────────────────────

    fun encryptWithRsa(data: ByteArray, publicKey: PublicKey): ByteArray {
        val cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding")
        cipher.init(Cipher.ENCRYPT_MODE, publicKey)
        return cipher.doFinal(data)
    }

    fun decryptWithRsa(data: ByteArray, privateKey: PrivateKey): ByteArray {
        val cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding")
        cipher.init(Cipher.DECRYPT_MODE, privateKey)
        return cipher.doFinal(data)
    }

    // ─── AES-256-GCM (command channel) ───────────────────────────────────────────────

    fun newAesKey(): SecretKey = KeyGenerator.getInstance("AES").apply { init(AES_KEY_SIZE) }.generateKey()

    fun aesKeyFromBytes(bytes: ByteArray): SecretKey = SecretKeySpec(bytes, "AES")

    /** Encrypt [plaintext] → Base64(iv ‖ ciphertext+tag). */
    fun encryptCommand(plaintext: String, sessionKey: SecretKey): String {
        val iv = ByteArray(GCM_IV_SIZE_BYTES).also { SecureRandom().nextBytes(it) }
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, sessionKey, GCMParameterSpec(GCM_TAG_SIZE_BITS, iv))
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        return Base64.encodeToString(iv + ciphertext, Base64.NO_WRAP)
    }

    /** Decrypt Base64(iv ‖ ciphertext+tag) → plaintext, or null on failure. */
    fun decryptCommand(encryptedB64: String, sessionKey: SecretKey): String? {
        return try {
            val data = Base64.decode(encryptedB64, Base64.NO_WRAP)
            val iv = data.sliceArray(0 until GCM_IV_SIZE_BYTES)
            val ciphertext = data.sliceArray(GCM_IV_SIZE_BYTES until data.size)
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            cipher.init(Cipher.DECRYPT_MODE, sessionKey, GCMParameterSpec(GCM_TAG_SIZE_BITS, iv))
            String(cipher.doFinal(ciphertext), Charsets.UTF_8)
        } catch (e: Exception) {
            android.util.Log.w("LAUNCHPAD", "QR decrypt failed", e)
            null
        }
    }

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }
}

/**
 * Pairing payload encoded into the QR shown by the launcher (or generated by the parent app).
 * Round-trips via org.json.
 */
data class QrPayloadJson(
    val version: String,
    val identity: String,        // launcher id (or parent id, depending on direction)
    val publicKeyB64: String,    // Base64 X509 RSA public key
    val nonceHex: String,
    val timestamp: Long,
    val persistent: Boolean = true
) {
    fun toJson(): String = JSONObject().apply {
        put("version", version)
        put("identity", identity)
        put("publicKeyB64", publicKeyB64)
        put("nonceHex", nonceHex)
        put("timestamp", timestamp)
        put("persistent", persistent)
    }.toString()

    companion object {
        fun fromJson(json: String): QrPayloadJson {
            val o = JSONObject(json)
            return QrPayloadJson(
                version = o.optString("version", QrPairingProtocol.PROTOCOL_VERSION),
                identity = o.optString("identity", ""),
                publicKeyB64 = o.optString("publicKeyB64", ""),
                nonceHex = o.optString("nonceHex", ""),
                timestamp = o.optLong("timestamp", 0L),
                persistent = o.optBoolean("persistent", true)
            )
        }
    }
}
